# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: A workflow to validate PRs

on:
  push:
  pull_request:
    branches: [ ocp-master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: echo -n -e "var OCL_API_HOST = 'https://api.staging.openconceptlab.org';" > public/env-config.js
      - run: npm install
      - run: npm run test
      - run: npm run test:integration
